### ISSUE TITLE
Visualizer hangs when hovering over a channel

### ISSUE THREAD

**Issue by pablo-ml** [rabbitmq/rabbitmq-management-visualiser#7]
When the mouse hovers over a channel, visualizer shows the channel information and it stops responding to other hover mouse events.

I can see an error in the js console:

model.js:238 Uncaught TypeError: Cannot read property 'name' of undefined

This is for:

Google Chrome Version 53.0.2785.101 (64-bit)
RabbitMQ Version: 3.5.7-1
Ubuntu 16-04

**Comment by michaelklishin** [comment]
This project is no longer maintained and no longer included into RabbitMQ releases. Thank you for reporting this but I'd like to be clear that this won't be a high priority for our team.

**Comment by michaelklishin** [comment]
Closing as #11 will be the last issue in this plugin before it's deprecated entirely.
