### ISSUE TITLE
GET /api/all tries to serialise pids into JSON and fails

### ISSUE THREAD

**Issue by mojtabye** [rabbitmq/rabbitmq-management-visualiser#8]
RabbitMQ Visualiser is not working for me :(
<img width="1407" alt="screen shot 2017-04-13 at 5 34 01 pm" src="https://cloud.githubusercontent.com/assets/13944347/25005860/d28d2bba-206f-11e7-8ec7-71660fad0c69.png">

I am using `CentOS Linux release 7.3.1611 RabbitMQ 3.6.9, Erlang 19.3`.
I tried to downgrad erlang from [erlang-rpm](https://github.com/rabbitmq/erlang-rpm/releases) to bellow versions but not working :(

1. erlang-19.3.0
2. erlang-19.2.3
3. erlang-18.3.4-5

`500 Internal Server Error`
`http://192.168.210.29:15672/api/all`

`{"error":"JSON encode error: {bad_term,<0.269.0>}","reason":"While encoding: \n[{queues,\n     [[{memory,26880},\n       {idle_since,<<\"2017-04-13 14:02:50\">>},\n       {consumer_utilisation,''},\n       {policy,''},\n       {exclusive_consumer_tag,''},\n       {consumers,0},\n       {recoverable_slaves,''},\n       {state,running},\n       {garbage_collection,\n           [{max_heap_size,0},\n            {min_bin_vheap_size,46422},\n            {min_heap_size,233},\n            {fullsweep_after,65535},\n            {minor_gcs,6}]},\n       {messages_ram,0},\n       {messages_ready_ram,0},\n       {messages_unacknowledged_ram,0},\n       {messages_persistent,0},\n       {message_bytes,0},\n       {message_bytes_ready,0},\n       {message_bytes_unacknowledged,0},\n       {message_bytes_ram,0},\n       {message_bytes_persistent,0},\n       {head_message_timestamp,''},\n       {backing_queue_status,\n           {struct,\n               [{mode,default},\n                {q1,0},\n                {q2,0},\n                {delta,[delta,0,0,0,0]},\n                {q3,0},\n                {q4,0},\n                {len,0},\n                {target_ram_count,infinity},\n                {next_seq_id,0},\n                {avg_ingress_rate,0.0},\n                {avg_egress_rate,0.0},\n                {avg_ack_ingress_rate,0.0},\n                {avg_ack_egress_rate,0.0}]}},\n       {messages_paged_out,0},\n       {message_bytes_paged_out,0},\n       {name,<<\"DBConsumer\">>},\n       {vhost,<<\"/\">>},\n       {durable,true},\n       {auto_delete,false},\n       {exclusive,false},\n       {owner_pid,none},\n       {arguments,{struct,[]}},\n       {pid,<0.269.0>},\n       {reductions,5023},\n       {reductions_details,[{rate,0.0}]},\n       {messages_ready,0},\n       {messages_ready_details,[{rate,0.0}]},\n       {messages_unacknowledged,0},\n       {messages_unacknowledged_details,[{rate,0.0}]},\n       {messages,0},\n       {messages_details,[{rate,0.0}]}],\n      [{memory,13090336},\n       {idle_since,<<\"2017-04-13 14:03:02\">>},\n       {consumer_utilisation,''},\n       {policy,''},\n       {exclusive_consumer_tag,''},\n       {consumers,0},\n       {recoverable_slaves,''},\n       {state,running},\n       {garbage_collection,\n           [{max_heap_size,0},\n            {min_bin_vheap_size,46422},\n            {min_heap_size,233},\n            {fullsweep_after,65535},\n            {minor_gcs,4}]},\n       {messages_ram,15294},\n       {messages_ready_ram,15294},\n       {messages_unacknowledged_ram,0},\n       {messages_persistent,468314},\n       {message_bytes,165813318},\n       {message_bytes_ready,165813318},\n       {message_bytes_unacknowledged,0},\n       {message_bytes_ram,5928988},\n       {message_bytes_persistent,165813318},\n       {head_message_timestamp,''},\n       {backing_queue_status,\n           {struct,\n               [{mode,default},\n                {q1,0},\n                {q2,0},\n                {delta,[delta,16384,453020,0,475136]},\n                {q3,15293},\n                {q4,1},\n                {len,468314},\n                {target_ram_count,infinity},\n                {next_seq_id,475136},\n                {avg_ingress_rate,0.0},\n                {avg_egress_rate,0.0},\n                {avg_ack_ingress_rate,0.0},\n                {avg_ack_egress_rate,0.0}]}},\n       {messages_paged_out,0},\n       {message_bytes_paged_out,0},\n       {name,<<\"DataProviderConsumer\">>},\n       {vhost,<<\"/\">>},\n       {durable,true},\n       {auto_delete,false},\n       {exclusive,false},\n       {owner_pid,none},\n       {arguments,{struct,[]}},\n       {pid,<0.272.0>},\n       {reductions,936890},\n       {reductions_details,[{rate,0.0}]},\n       {messages_ready,468314},\n       {messages_ready_details,[{rate,0.0}]},\n       {messages_unacknowledged,0},\n       {messages_unacknowledged_details,[{rate,0.0}]},\n       {messages,468314},\n       {messages_details,[{rate,0.0}]}]]},\n {exchanges,\n     [[{name,<<>>},\n       {vhost,<<\"/\">>},\n       {type,direct},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"DataProvider\">>},\n       {vhost,<<\"/\">>},\n       {type,topic},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.rabbitmq.log\">>},\n       {vhost,<<\"/\">>},\n       {type,topic},\n       {durable,true},\n       {auto_delete,false},\n       {internal,true},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.headers\">>},\n       {vhost,<<\"/\">>},\n       {type,headers},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.topic\">>},\n       {vhost,<<\"/\">>},\n       {type,topic},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.match\">>},\n       {vhost,<<\"/\">>},\n       {type,headers},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.rabbitmq.trace\">>},\n       {vhost,<<\"/\">>},\n       {type,topic},\n       {durable,true},\n       {auto_delete,false},\n       {internal,true},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.direct\">>},\n       {vhost,<<\"/\">>},\n       {type,direct},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.fanout\">>},\n       {vhost,<<\"/\">>},\n       {type,fanout},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}]]},\n {bindings,\n     [[{source,<<>>},\n       {vhost,<<\"/\">>},\n       {destination,<<\"DBConsumer\">>},\n       {destination_type,queue},\n       {routing_key,<<\"DBConsumer\">>},\n       {arguments,{struct,[]}},\n       {properties_key,<<\"DBConsumer\">>}],\n      [{source,<<>>},\n       {vhost,<<\"/\">>},\n       {destination,<<\"DataProviderConsumer\">>},\n       {destination_type,queue},\n       {routing_key,<<\"DataProviderConsumer\">>},\n       {arguments,{struct,[]}},\n       {properties_key,<<\"DataProviderConsumer\">>}],\n      [{source,<<\"DataProvider\">>},\n       {vhost,<<\"/\">>},\n       {destination,<<\"DataProviderConsumer\">>},\n       {destination_type,queue},\n       {routing_key,<<\"#\">>},\n       {arguments,{struct,[]}},\n       {properties_key,<<\"%23\">>}],\n      [{source,<<\"DataProvider\">>},\n       {vhost,<<\"/\">>},\n       {destination,<<\"DBConsumer\">>},\n       {destination_type,queue},\n       {routing_key,<<\"#.TRADE\">>},\n       {arguments,{struct,[]}},\n       {properties_key,<<\"%23.TRADE\">>}]]},\n {channels,[]},\n {connections,[]},\n {vhosts,\n     [[{name,<<\"/\">>},\n       {tracing,false},\n       {messages_ready,468314},\n       {messages_ready_details,[{rate,0.0}]},\n       {messages_unacknowledged,0},\n       {messages_unacknowledged_details,[{rate,0.0}]},\n       {messages,468314},\n       {messages_details,[{rate,0.0}]}]]}]"}`

**Comment by michaelklishin** [comment]
This very likely has nothing to do with the visualizer. HTTP API fails to serialize a particular data set to JSON because it contains a pid, a type that has no meaningful representation in JSON. We've fixed a bunch of those since 3.6.8 but it's not clear what the 

Please post a step by step way to reproduce this as well as a screenshot of the network requests tab from your browser's developer tools and logs to rabbitmq-users. We will be happy to file a new issue once we understand what's going on and if it's something new. Thanks.

**Comment by michaelklishin** [comment]
So `/api/all` [does come](https://github.com/rabbitmq/rabbitmq-management-visualiser/blob/master/src/rabbit_mgmt_wm_all.erl) from this plugin. We'll fix it but as an FYI, this plugin won't ship with RabbitMQ 3.7.0 and won't be updated for much longer. I would not depend on it too much.
